namespace PokeBinder.TcgCatalog.DbContext.Entities;

/// <summary>
/// The current stamp for one <see cref="FilterCacheGroup"/>: the value a client compares against
/// its own stored copy of that group to decide whether it has to be re-fetched.
/// <para>
/// The stamp is opaque and compared for equality only. It says "not what you have", never "newer
/// than what you have", so nothing about it needs to be ordered, monotonic or meaningful -- which
/// is what lets it be regenerated by hand from the admin screen without a scheme to maintain.
/// </para>
/// </summary>
public class FilterCacheStamp
{
    /// <summary>The group this stamp belongs to, and the row's key: one stamp per group.</summary>
    public FilterCacheGroup Group { get; set; }

    /// <summary>
    /// The current value, a GUID in string form. Replaced wholesale on a bump; never edited.
    /// </summary>
    public string Stamp { get; set; } = string.Empty;

    /// <summary>
    /// When the stamp last changed. Unix time in seconds, UTC. Nothing reads this to make a
    /// decision -- the comparison is on <see cref="Stamp"/> alone -- it exists so the admin screen
    /// can show when a group was last invalidated.
    /// </summary>
    public long LastBumpedUnix { get; set; }
}
