using FluentMigrator;

namespace PokeBinder.FluentMigrator.Migrations.TcgCatalog;

[Migration(20250325_000002)]
[Tags(DatabaseTags.TcgCatalog)]
public class CreatePokemonFilterOptions : Migration
{
    public override void Up()
    {
        Create.Table("generationFilterOptions")
            .WithColumn("id").AsInt32().PrimaryKey().Identity()
            .WithColumn("name").AsString(63).NotNullable();

        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation I" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation II" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation III" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation IV" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation V" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation VI" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation VII" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation VIII" });
        Insert.IntoTable("generationFilterOptions").Row(new { name = "Generation IX" });

        Create.Table("pokemonFilterOptions")
            .WithColumn("id").AsInt32().PrimaryKey().Identity()
            .WithColumn("pokedexNumber").AsInt32().NotNullable()
            .WithColumn("name").AsString(255).NotNullable()
            .WithColumn("generationId").AsInt32().NotNullable()
                .ForeignKey("FK_pokemonFilterOptions_generationFilterOptions", "generationFilterOptions", "id")
            .WithColumn("alternateName").AsString(255).Nullable();

        foreach (var (dexNum, name, genId, altName) in GetAllPokemon())
        {
            Insert.IntoTable("pokemonFilterOptions").Row(new
            {
                pokedexNumber = dexNum,
                name,
                generationId = genId,
                alternateName = altName ?? ""
            });
        }
    }

    public override void Down()
    {
        Delete.Table("pokemonFilterOptions");
        Delete.Table("generationFilterOptions");
    }

    private static List<(int DexNum, string Name, int GenerationId, string? AltName)> GetAllPokemon()
    {
        return
        [
            // Generation I (Kanto) #1-151
            (1, "Bulbasaur", 1, null),
            (2, "Ivysaur", 1, null),
            (3, "Venusaur", 1, null),
            (4, "Charmander", 1, null),
            (5, "Charmeleon", 1, null),
            (6, "Charizard", 1, null),
            (7, "Squirtle", 1, null),
            (8, "Wartortle", 1, null),
            (9, "Blastoise", 1, null),
            (10, "Caterpie", 1, null),
            (11, "Metapod", 1, null),
            (12, "Butterfree", 1, null),
            (13, "Weedle", 1, null),
            (14, "Kakuna", 1, null),
            (15, "Beedrill", 1, null),
            (16, "Pidgey", 1, null),
            (17, "Pidgeotto", 1, null),
            (18, "Pidgeot", 1, null),
            (19, "Rattata", 1, null),
            (20, "Raticate", 1, null),
            (21, "Spearow", 1, null),
            (22, "Fearow", 1, null),
            (23, "Ekans", 1, null),
            (24, "Arbok", 1, null),
            (25, "Pikachu", 1, null),
            (26, "Raichu", 1, null),
            (27, "Sandshrew", 1, null),
            (28, "Sandslash", 1, null),
            (29, "Nidoran♀", 1, null),
            (30, "Nidorina", 1, null),
            (31, "Nidoqueen", 1, null),
            (32, "Nidoran♂", 1, null),
            (33, "Nidorino", 1, null),
            (34, "Nidoking", 1, null),
            (35, "Clefairy", 1, null),
            (36, "Clefable", 1, null),
            (37, "Vulpix", 1, null),
            (38, "Ninetales", 1, null),
            (39, "Jigglypuff", 1, null),
            (40, "Wigglytuff", 1, null),
            (41, "Zubat", 1, null),
            (42, "Golbat", 1, null),
            (43, "Oddish", 1, null),
            (44, "Gloom", 1, null),
            (45, "Vileplume", 1, null),
            (46, "Paras", 1, null),
            (47, "Parasect", 1, null),
            (48, "Venonat", 1, null),
            (49, "Venomoth", 1, null),
            (50, "Diglett", 1, null),
            (51, "Dugtrio", 1, null),
            (52, "Meowth", 1, null),
            (53, "Persian", 1, null),
            (54, "Psyduck", 1, null),
            (55, "Golduck", 1, null),
            (56, "Mankey", 1, null),
            (57, "Primeape", 1, null),
            (58, "Growlithe", 1, null),
            (59, "Arcanine", 1, null),
            (60, "Poliwag", 1, null),
            (61, "Poliwhirl", 1, null),
            (62, "Poliwrath", 1, null),
            (63, "Abra", 1, null),
            (64, "Kadabra", 1, null),
            (65, "Alakazam", 1, null),
            (66, "Machop", 1, null),
            (67, "Machoke", 1, null),
            (68, "Machamp", 1, null),
            (69, "Bellsprout", 1, null),
            (70, "Weepinbell", 1, null),
            (71, "Victreebel", 1, null),
            (72, "Tentacool", 1, null),
            (73, "Tentacruel", 1, null),
            (74, "Geodude", 1, null),
            (75, "Graveler", 1, null),
            (76, "Golem", 1, null),
            (77, "Ponyta", 1, null),
            (78, "Rapidash", 1, null),
            (79, "Slowpoke", 1, null),
            (80, "Slowbro", 1, null),
            (81, "Magnemite", 1, null),
            (82, "Magneton", 1, null),
            (83, "Farfetch'd", 1, null),
            (84, "Doduo", 1, null),
            (85, "Dodrio", 1, null),
            (86, "Seel", 1, null),
            (87, "Dewgong", 1, null),
            (88, "Grimer", 1, null),
            (89, "Muk", 1, null),
            (90, "Shellder", 1, null),
            (91, "Cloyster", 1, null),
            (92, "Gastly", 1, null),
            (93, "Haunter", 1, null),
            (94, "Gengar", 1, null),
            (95, "Onix", 1, null),
            (96, "Drowzee", 1, null),
            (97, "Hypno", 1, null),
            (98, "Krabby", 1, null),
            (99, "Kingler", 1, null),
            (100, "Voltorb", 1, null),
            (101, "Electrode", 1, null),
            (102, "Exeggcute", 1, null),
            (103, "Exeggutor", 1, null),
            (104, "Cubone", 1, null),
            (105, "Marowak", 1, null),
            (106, "Hitmonlee", 1, null),
            (107, "Hitmonchan", 1, null),
            (108, "Lickitung", 1, null),
            (109, "Koffing", 1, null),
            (110, "Weezing", 1, null),
            (111, "Rhyhorn", 1, null),
            (112, "Rhydon", 1, null),
            (113, "Chansey", 1, null),
            (114, "Tangela", 1, null),
            (115, "Kangaskhan", 1, null),
            (116, "Horsea", 1, null),
            (117, "Seadra", 1, null),
            (118, "Goldeen", 1, null),
            (119, "Seaking", 1, null),
            (120, "Staryu", 1, null),
            (121, "Starmie", 1, null),
            (122, "Mr. Mime", 1, null),
            (123, "Scyther", 1, null),
            (124, "Jynx", 1, null),
            (125, "Electabuzz", 1, null),
            (126, "Magmar", 1, null),
            (127, "Pinsir", 1, null),
            (128, "Tauros", 1, null),
            (129, "Magikarp", 1, null),
            (130, "Gyarados", 1, null),
            (131, "Lapras", 1, null),
            (132, "Ditto", 1, null),
            (133, "Eevee", 1, null),
            (134, "Vaporeon", 1, null),
            (135, "Jolteon", 1, null),
            (136, "Flareon", 1, null),
            (137, "Porygon", 1, null),
            (138, "Omanyte", 1, null),
            (139, "Omastar", 1, null),
            (140, "Kabuto", 1, null),
            (141, "Kabutops", 1, null),
            (142, "Aerodactyl", 1, null),
            (143, "Snorlax", 1, null),
            (144, "Articuno", 1, null),
            (145, "Zapdos", 1, null),
            (146, "Moltres", 1, null),
            (147, "Dratini", 1, null),
            (148, "Dragonair", 1, null),
            (149, "Dragonite", 1, null),
            (150, "Mewtwo", 1, null),
            (151, "Mew", 1, null),

            // Generation II (Johto) #152-251
            (152, "Chikorita", 2, null),
            (153, "Bayleef", 2, null),
            (154, "Meganium", 2, null),
            (155, "Cyndaquil", 2, null),
            (156, "Quilava", 2, null),
            (157, "Typhlosion", 2, null),
            (158, "Totodile", 2, null),
            (159, "Croconaw", 2, null),
            (160, "Feraligatr", 2, null),
            (161, "Sentret", 2, null),
            (162, "Furret", 2, null),
            (163, "Hoothoot", 2, null),
            (164, "Noctowl", 2, null),
            (165, "Ledyba", 2, null),
            (166, "Ledian", 2, null),
            (167, "Spinarak", 2, null),
            (168, "Ariados", 2, null),
            (169, "Crobat", 2, null),
            (170, "Chinchou", 2, null),
            (171, "Lanturn", 2, null),
            (172, "Pichu", 2, null),
            (173, "Cleffa", 2, null),
            (174, "Igglybuff", 2, null),
            (175, "Togepi", 2, null),
            (176, "Togetic", 2, null),
            (177, "Natu", 2, null),
            (178, "Xatu", 2, null),
            (179, "Mareep", 2, null),
            (180, "Flaaffy", 2, null),
            (181, "Ampharos", 2, null),
            (182, "Bellossom", 2, null),
            (183, "Marill", 2, null),
            (184, "Azumarill", 2, null),
            (185, "Sudowoodo", 2, null),
            (186, "Politoed", 2, null),
            (187, "Hoppip", 2, null),
            (188, "Skiploom", 2, null),
            (189, "Jumpluff", 2, null),
            (190, "Aipom", 2, null),
            (191, "Sunkern", 2, null),
            (192, "Sunflora", 2, null),
            (193, "Yanma", 2, null),
            (194, "Wooper", 2, null),
            (195, "Quagsire", 2, null),
            (196, "Espeon", 2, null),
            (197, "Umbreon", 2, null),
            (198, "Murkrow", 2, null),
            (199, "Slowking", 2, null),
            (200, "Misdreavus", 2, null),
            (201, "Unown", 2, null),
            (202, "Wobbuffet", 2, null),
            (203, "Girafarig", 2, null),
            (204, "Pineco", 2, null),
            (205, "Forretress", 2, null),
            (206, "Dunsparce", 2, null),
            (207, "Gligar", 2, null),
            (208, "Steelix", 2, null),
            (209, "Snubbull", 2, null),
            (210, "Granbull", 2, null),
            (211, "Qwilfish", 2, null),
            (212, "Scizor", 2, null),
            (213, "Shuckle", 2, null),
            (214, "Heracross", 2, null),
            (215, "Sneasel", 2, null),
            (216, "Teddiursa", 2, null),
            (217, "Ursaring", 2, null),
            (218, "Slugma", 2, null),
            (219, "Magcargo", 2, null),
            (220, "Swinub", 2, null),
            (221, "Piloswine", 2, null),
            (222, "Corsola", 2, null),
            (223, "Remoraid", 2, null),
            (224, "Octillery", 2, null),
            (225, "Delibird", 2, null),
            (226, "Mantine", 2, null),
            (227, "Skarmory", 2, null),
            (228, "Houndour", 2, null),
            (229, "Houndoom", 2, null),
            (230, "Kingdra", 2, null),
            (231, "Phanpy", 2, null),
            (232, "Donphan", 2, null),
            (233, "Porygon2", 2, null),
            (234, "Stantler", 2, null),
            (235, "Smeargle", 2, null),
            (236, "Tyrogue", 2, null),
            (237, "Hitmontop", 2, null),
            (238, "Smoochum", 2, null),
            (239, "Elekid", 2, null),
            (240, "Magby", 2, null),
            (241, "Miltank", 2, null),
            (242, "Blissey", 2, null),
            (243, "Raikou", 2, null),
            (244, "Entei", 2, null),
            (245, "Suicune", 2, null),
            (246, "Larvitar", 2, null),
            (247, "Pupitar", 2, null),
            (248, "Tyranitar", 2, null),
            (249, "Lugia", 2, null),
            (250, "Ho-Oh", 2, null),
            (251, "Celebi", 2, null),

            // Generation III (Hoenn) #252-386
            (252, "Treecko", 3, null),
            (253, "Grovyle", 3, null),
            (254, "Sceptile", 3, null),
            (255, "Torchic", 3, null),
            (256, "Combusken", 3, null),
            (257, "Blaziken", 3, null),
            (258, "Mudkip", 3, null),
            (259, "Marshtomp", 3, null),
            (260, "Swampert", 3, null),
            (261, "Poochyena", 3, null),
            (262, "Mightyena", 3, null),
            (263, "Zigzagoon", 3, null),
            (264, "Linoone", 3, null),
            (265, "Wurmple", 3, null),
            (266, "Silcoon", 3, null),
            (267, "Beautifly", 3, null),
            (268, "Cascoon", 3, null),
            (269, "Dustox", 3, null),
            (270, "Lotad", 3, null),
            (271, "Lombre", 3, null),
            (272, "Ludicolo", 3, null),
            (273, "Seedot", 3, null),
            (274, "Nuzleaf", 3, null),
            (275, "Shiftry", 3, null),
            (276, "Taillow", 3, null),
            (277, "Swellow", 3, null),
            (278, "Wingull", 3, null),
            (279, "Pelipper", 3, null),
            (280, "Ralts", 3, null),
            (281, "Kirlia", 3, null),
            (282, "Gardevoir", 3, null),
            (283, "Surskit", 3, null),
            (284, "Masquerain", 3, null),
            (285, "Shroomish", 3, null),
            (286, "Breloom", 3, null),
            (287, "Slakoth", 3, null),
            (288, "Vigoroth", 3, null),
            (289, "Slaking", 3, null),
            (290, "Nincada", 3, null),
            (291, "Ninjask", 3, null),
            (292, "Shedinja", 3, null),
            (293, "Whismur", 3, null),
            (294, "Loudred", 3, null),
            (295, "Exploud", 3, null),
            (296, "Makuhita", 3, null),
            (297, "Hariyama", 3, null),
            (298, "Azurill", 3, null),
            (299, "Nosepass", 3, null),
            (300, "Skitty", 3, null),
            (301, "Delcatty", 3, null),
            (302, "Sableye", 3, null),
            (303, "Mawile", 3, null),
            (304, "Aron", 3, null),
            (305, "Lairon", 3, null),
            (306, "Aggron", 3, null),
            (307, "Meditite", 3, null),
            (308, "Medicham", 3, null),
            (309, "Electrike", 3, null),
            (310, "Manectric", 3, null),
            (311, "Plusle", 3, null),
            (312, "Minun", 3, null),
            (313, "Volbeat", 3, null),
            (314, "Illumise", 3, null),
            (315, "Roselia", 3, null),
            (316, "Gulpin", 3, null),
            (317, "Swalot", 3, null),
            (318, "Carvanha", 3, null),
            (319, "Sharpedo", 3, null),
            (320, "Wailmer", 3, null),
            (321, "Wailord", 3, null),
            (322, "Numel", 3, null),
            (323, "Camerupt", 3, null),
            (324, "Torkoal", 3, null),
            (325, "Spoink", 3, null),
            (326, "Grumpig", 3, null),
            (327, "Spinda", 3, null),
            (328, "Trapinch", 3, null),
            (329, "Vibrava", 3, null),
            (330, "Flygon", 3, null),
            (331, "Cacnea", 3, null),
            (332, "Cacturne", 3, null),
            (333, "Swablu", 3, null),
            (334, "Altaria", 3, null),
            (335, "Zangoose", 3, null),
            (336, "Seviper", 3, null),
            (337, "Lunatone", 3, null),
            (338, "Solrock", 3, null),
            (339, "Barboach", 3, null),
            (340, "Whiscash", 3, null),
            (341, "Corphish", 3, null),
            (342, "Crawdaunt", 3, null),
            (343, "Baltoy", 3, null),
            (344, "Claydol", 3, null),
            (345, "Lileep", 3, null),
            (346, "Cradily", 3, null),
            (347, "Anorith", 3, null),
            (348, "Armaldo", 3, null),
            (349, "Feebas", 3, null),
            (350, "Milotic", 3, null),
            (351, "Castform", 3, null),
            (352, "Kecleon", 3, null),
            (353, "Shuppet", 3, null),
            (354, "Banette", 3, null),
            (355, "Duskull", 3, null),
            (356, "Dusclops", 3, null),
            (357, "Tropius", 3, null),
            (358, "Chimecho", 3, null),
            (359, "Absol", 3, null),
            (360, "Wynaut", 3, null),
            (361, "Snorunt", 3, null),
            (362, "Glalie", 3, null),
            (363, "Spheal", 3, null),
            (364, "Sealeo", 3, null),
            (365, "Walrein", 3, null),
            (366, "Clamperl", 3, null),
            (367, "Huntail", 3, null),
            (368, "Gorebyss", 3, null),
            (369, "Relicanth", 3, null),
            (370, "Luvdisc", 3, null),
            (371, "Bagon", 3, null),
            (372, "Shelgon", 3, null),
            (373, "Salamence", 3, null),
            (374, "Beldum", 3, null),
            (375, "Metang", 3, null),
            (376, "Metagross", 3, null),
            (377, "Regirock", 3, null),
            (378, "Regice", 3, null),
            (379, "Registeel", 3, null),
            (380, "Latias", 3, null),
            (381, "Latios", 3, null),
            (382, "Kyogre", 3, null),
            (383, "Groudon", 3, null),
            (384, "Rayquaza", 3, null),
            (385, "Jirachi", 3, null),
            (386, "Deoxys", 3, null),

            // Generation IV (Sinnoh) #387-493
            (387, "Turtwig", 4, null),
            (388, "Grotle", 4, null),
            (389, "Torterra", 4, null),
            (390, "Chimchar", 4, null),
            (391, "Monferno", 4, null),
            (392, "Infernape", 4, null),
            (393, "Piplup", 4, null),
            (394, "Prinplup", 4, null),
            (395, "Empoleon", 4, null),
            (396, "Starly", 4, null),
            (397, "Staravia", 4, null),
            (398, "Staraptor", 4, null),
            (399, "Bidoof", 4, null),
            (400, "Bibarel", 4, null),
            (401, "Kricketot", 4, null),
            (402, "Kricketune", 4, null),
            (403, "Shinx", 4, null),
            (404, "Luxio", 4, null),
            (405, "Luxray", 4, null),
            (406, "Budew", 4, null),
            (407, "Roserade", 4, null),
            (408, "Cranidos", 4, null),
            (409, "Rampardos", 4, null),
            (410, "Shieldon", 4, null),
            (411, "Bastiodon", 4, null),
            (412, "Burmy", 4, null),
            (413, "Wormadam", 4, null),
            (414, "Mothim", 4, null),
            (415, "Combee", 4, null),
            (416, "Vespiquen", 4, null),
            (417, "Pachirisu", 4, null),
            (418, "Buizel", 4, null),
            (419, "Floatzel", 4, null),
            (420, "Cherubi", 4, null),
            (421, "Cherrim", 4, null),
            (422, "Shellos", 4, null),
            (423, "Gastrodon", 4, null),
            (424, "Ambipom", 4, null),
            (425, "Drifloon", 4, null),
            (426, "Drifblim", 4, null),
            (427, "Buneary", 4, null),
            (428, "Lopunny", 4, null),
            (429, "Mismagius", 4, null),
            (430, "Honchkrow", 4, null),
            (431, "Glameow", 4, null),
            (432, "Purugly", 4, null),
            (433, "Chingling", 4, null),
            (434, "Stunky", 4, null),
            (435, "Skuntank", 4, null),
            (436, "Bronzor", 4, null),
            (437, "Bronzong", 4, null),
            (438, "Bonsly", 4, null),
            (439, "Mime Jr.", 4, null),
            (440, "Happiny", 4, null),
            (441, "Chatot", 4, null),
            (442, "Spiritomb", 4, null),
            (443, "Gible", 4, null),
            (444, "Gabite", 4, null),
            (445, "Garchomp", 4, null),
            (446, "Munchlax", 4, null),
            (447, "Riolu", 4, null),
            (448, "Lucario", 4, null),
            (449, "Hippopotas", 4, null),
            (450, "Hippowdon", 4, null),
            (451, "Skorupi", 4, null),
            (452, "Drapion", 4, null),
            (453, "Croagunk", 4, null),
            (454, "Toxicroak", 4, null),
            (455, "Carnivine", 4, null),
            (456, "Finneon", 4, null),
            (457, "Lumineon", 4, null),
            (458, "Mantyke", 4, null),
            (459, "Snover", 4, null),
            (460, "Abomasnow", 4, null),
            (461, "Weavile", 4, null),
            (462, "Magnezone", 4, null),
            (463, "Lickilicky", 4, null),
            (464, "Rhyperior", 4, null),
            (465, "Tangrowth", 4, null),
            (466, "Electivire", 4, null),
            (467, "Magmortar", 4, null),
            (468, "Togekiss", 4, null),
            (469, "Yanmega", 4, null),
            (470, "Leafeon", 4, null),
            (471, "Glaceon", 4, null),
            (472, "Gliscor", 4, null),
            (473, "Mamoswine", 4, null),
            (474, "Porygon-Z", 4, null),
            (475, "Gallade", 4, null),
            (476, "Probopass", 4, null),
            (477, "Dusknoir", 4, null),
            (478, "Froslass", 4, null),
            (479, "Rotom", 4, null),
            (480, "Uxie", 4, null),
            (481, "Mesprit", 4, null),
            (482, "Azelf", 4, null),
            (483, "Dialga", 4, null),
            (484, "Palkia", 4, null),
            (485, "Heatran", 4, null),
            (486, "Regigigas", 4, null),
            (487, "Giratina", 4, null),
            (488, "Cresselia", 4, null),
            (489, "Phione", 4, null),
            (490, "Manaphy", 4, null),
            (491, "Darkrai", 4, null),
            (492, "Shaymin", 4, null),
            (493, "Arceus", 4, null),

            // Generation V (Unova) #494-649
            (494, "Victini", 5, null),
            (495, "Snivy", 5, null),
            (496, "Servine", 5, null),
            (497, "Serperior", 5, null),
            (498, "Tepig", 5, null),
            (499, "Pignite", 5, null),
            (500, "Emboar", 5, null),
            (501, "Oshawott", 5, null),
            (502, "Dewott", 5, null),
            (503, "Samurott", 5, null),
            (504, "Patrat", 5, null),
            (505, "Watchog", 5, null),
            (506, "Lillipup", 5, null),
            (507, "Herdier", 5, null),
            (508, "Stoutland", 5, null),
            (509, "Purrloin", 5, null),
            (510, "Liepard", 5, null),
            (511, "Pansage", 5, null),
            (512, "Simisage", 5, null),
            (513, "Pansear", 5, null),
            (514, "Simisear", 5, null),
            (515, "Panpour", 5, null),
            (516, "Simipour", 5, null),
            (517, "Munna", 5, null),
            (518, "Musharna", 5, null),
            (519, "Pidove", 5, null),
            (520, "Tranquill", 5, null),
            (521, "Unfezant", 5, null),
            (522, "Blitzle", 5, null),
            (523, "Zebstrika", 5, null),
            (524, "Roggenrola", 5, null),
            (525, "Boldore", 5, null),
            (526, "Gigalith", 5, null),
            (527, "Woobat", 5, null),
            (528, "Swoobat", 5, null),
            (529, "Drilbur", 5, null),
            (530, "Excadrill", 5, null),
            (531, "Audino", 5, null),
            (532, "Timburr", 5, null),
            (533, "Gurdurr", 5, null),
            (534, "Conkeldurr", 5, null),
            (535, "Tympole", 5, null),
            (536, "Palpitoad", 5, null),
            (537, "Seismitoad", 5, null),
            (538, "Throh", 5, null),
            (539, "Sawk", 5, null),
            (540, "Sewaddle", 5, null),
            (541, "Swadloon", 5, null),
            (542, "Leavanny", 5, null),
            (543, "Venipede", 5, null),
            (544, "Whirlipede", 5, null),
            (545, "Scolipede", 5, null),
            (546, "Cottonee", 5, null),
            (547, "Whimsicott", 5, null),
            (548, "Petilil", 5, null),
            (549, "Lilligant", 5, null),
            (550, "Basculin", 5, null),
            (551, "Sandile", 5, null),
            (552, "Krokorok", 5, null),
            (553, "Krookodile", 5, null),
            (554, "Darumaka", 5, null),
            (555, "Darmanitan", 5, null),
            (556, "Maractus", 5, null),
            (557, "Dwebble", 5, null),
            (558, "Crustle", 5, null),
            (559, "Scraggy", 5, null),
            (560, "Scrafty", 5, null),
            (561, "Sigilyph", 5, null),
            (562, "Yamask", 5, null),
            (563, "Cofagrigus", 5, null),
            (564, "Tirtouga", 5, null),
            (565, "Carracosta", 5, null),
            (566, "Archen", 5, null),
            (567, "Archeops", 5, null),
            (568, "Trubbish", 5, null),
            (569, "Garbodor", 5, null),
            (570, "Zorua", 5, null),
            (571, "Zoroark", 5, null),
            (572, "Minccino", 5, null),
            (573, "Cinccino", 5, null),
            (574, "Gothita", 5, null),
            (575, "Gothorita", 5, null),
            (576, "Gothitelle", 5, null),
            (577, "Solosis", 5, null),
            (578, "Duosion", 5, null),
            (579, "Reuniclus", 5, null),
            (580, "Ducklett", 5, null),
            (581, "Swanna", 5, null),
            (582, "Vanillite", 5, null),
            (583, "Vanillish", 5, null),
            (584, "Vanilluxe", 5, null),
            (585, "Deerling", 5, null),
            (586, "Sawsbuck", 5, null),
            (587, "Emolga", 5, null),
            (588, "Karrablast", 5, null),
            (589, "Escavalier", 5, null),
            (590, "Foongus", 5, null),
            (591, "Amoonguss", 5, null),
            (592, "Frillish", 5, null),
            (593, "Jellicent", 5, null),
            (594, "Alomomola", 5, null),
            (595, "Joltik", 5, null),
            (596, "Galvantula", 5, null),
            (597, "Ferroseed", 5, null),
            (598, "Ferrothorn", 5, null),
            (599, "Klink", 5, null),
            (600, "Klang", 5, null),
            (601, "Klinklang", 5, null),
            (602, "Tynamo", 5, null),
            (603, "Eelektrik", 5, null),
            (604, "Eelektross", 5, null),
            (605, "Elgyem", 5, null),
            (606, "Beheeyem", 5, null),
            (607, "Litwick", 5, null),
            (608, "Lampent", 5, null),
            (609, "Chandelure", 5, null),
            (610, "Axew", 5, null),
            (611, "Fraxure", 5, null),
            (612, "Haxorus", 5, null),
            (613, "Cubchoo", 5, null),
            (614, "Beartic", 5, null),
            (615, "Cryogonal", 5, null),
            (616, "Shelmet", 5, null),
            (617, "Accelgor", 5, null),
            (618, "Stunfisk", 5, null),
            (619, "Mienfoo", 5, null),
            (620, "Mienshao", 5, null),
            (621, "Druddigon", 5, null),
            (622, "Golett", 5, null),
            (623, "Golurk", 5, null),
            (624, "Pawniard", 5, null),
            (625, "Bisharp", 5, null),
            (626, "Bouffalant", 5, null),
            (627, "Rufflet", 5, null),
            (628, "Braviary", 5, null),
            (629, "Vullaby", 5, null),
            (630, "Mandibuzz", 5, null),
            (631, "Heatmor", 5, null),
            (632, "Durant", 5, null),
            (633, "Deino", 5, null),
            (634, "Zweilous", 5, null),
            (635, "Hydreigon", 5, null),
            (636, "Larvesta", 5, null),
            (637, "Volcarona", 5, null),
            (638, "Cobalion", 5, null),
            (639, "Terrakion", 5, null),
            (640, "Virizion", 5, null),
            (641, "Tornadus", 5, null),
            (642, "Thundurus", 5, null),
            (643, "Reshiram", 5, null),
            (644, "Zekrom", 5, null),
            (645, "Landorus", 5, null),
            (646, "Kyurem", 5, null),
            (647, "Keldeo", 5, null),
            (648, "Meloetta", 5, null),
            (649, "Genesect", 5, null),

            // Generation VI (Kalos) #650-721
            (650, "Chespin", 6, null),
            (651, "Quilladin", 6, null),
            (652, "Chesnaught", 6, null),
            (653, "Fennekin", 6, null),
            (654, "Braixen", 6, null),
            (655, "Delphox", 6, null),
            (656, "Froakie", 6, null),
            (657, "Frogadier", 6, null),
            (658, "Greninja", 6, null),
            (659, "Bunnelby", 6, null),
            (660, "Diggersby", 6, null),
            (661, "Fletchling", 6, null),
            (662, "Fletchinder", 6, null),
            (663, "Talonflame", 6, null),
            (664, "Scatterbug", 6, null),
            (665, "Spewpa", 6, null),
            (666, "Vivillon", 6, null),
            (667, "Litleo", 6, null),
            (668, "Pyroar", 6, null),
            (669, "Flabébé", 6, null),
            (670, "Floette", 6, null),
            (671, "Florges", 6, null),
            (672, "Skiddo", 6, null),
            (673, "Gogoat", 6, null),
            (674, "Pancham", 6, null),
            (675, "Pangoro", 6, null),
            (676, "Furfrou", 6, null),
            (677, "Espurr", 6, null),
            (678, "Meowstic", 6, null),
            (679, "Honedge", 6, null),
            (680, "Doublade", 6, null),
            (681, "Aegislash", 6, null),
            (682, "Spritzee", 6, null),
            (683, "Aromatisse", 6, null),
            (684, "Swirlix", 6, null),
            (685, "Slurpuff", 6, null),
            (686, "Inkay", 6, null),
            (687, "Malamar", 6, null),
            (688, "Binacle", 6, null),
            (689, "Barbaracle", 6, null),
            (690, "Skrelp", 6, null),
            (691, "Dragalge", 6, null),
            (692, "Clauncher", 6, null),
            (693, "Clawitzer", 6, null),
            (694, "Helioptile", 6, null),
            (695, "Heliolisk", 6, null),
            (696, "Tyrunt", 6, null),
            (697, "Tyrantrum", 6, null),
            (698, "Amaura", 6, null),
            (699, "Aurorus", 6, null),
            (700, "Sylveon", 6, null),
            (701, "Hawlucha", 6, null),
            (702, "Dedenne", 6, null),
            (703, "Carbink", 6, null),
            (704, "Goomy", 6, null),
            (705, "Sliggoo", 6, null),
            (706, "Goodra", 6, null),
            (707, "Klefki", 6, null),
            (708, "Phantump", 6, null),
            (709, "Trevenant", 6, null),
            (710, "Pumpkaboo", 6, null),
            (711, "Gourgeist", 6, null),
            (712, "Bergmite", 6, null),
            (713, "Avalugg", 6, null),
            (714, "Noibat", 6, null),
            (715, "Noivern", 6, null),
            (716, "Xerneas", 6, null),
            (717, "Yveltal", 6, null),
            (718, "Zygarde", 6, null),
            (719, "Diancie", 6, null),
            (720, "Hoopa", 6, null),
            (721, "Volcanion", 6, null),

            // Generation VII (Alola) #722-809
            (722, "Rowlet", 7, null),
            (723, "Dartrix", 7, null),
            (724, "Decidueye", 7, null),
            (725, "Litten", 7, null),
            (726, "Torracat", 7, null),
            (727, "Incineroar", 7, null),
            (728, "Popplio", 7, null),
            (729, "Brionne", 7, null),
            (730, "Primarina", 7, null),
            (731, "Pikipek", 7, null),
            (732, "Trumbeak", 7, null),
            (733, "Toucannon", 7, null),
            (734, "Yungoos", 7, null),
            (735, "Gumshoos", 7, null),
            (736, "Grubbin", 7, null),
            (737, "Charjabug", 7, null),
            (738, "Vikavolt", 7, null),
            (739, "Crabrawler", 7, null),
            (740, "Crabominable", 7, null),
            (741, "Oricorio", 7, null),
            (742, "Cutiefly", 7, null),
            (743, "Ribombee", 7, null),
            (744, "Rockruff", 7, null),
            (745, "Lycanroc", 7, null),
            (746, "Wishiwashi", 7, null),
            (747, "Mareanie", 7, null),
            (748, "Toxapex", 7, null),
            (749, "Mudbray", 7, null),
            (750, "Mudsdale", 7, null),
            (751, "Dewpider", 7, null),
            (752, "Araquanid", 7, null),
            (753, "Fomantis", 7, null),
            (754, "Lurantis", 7, null),
            (755, "Morelull", 7, null),
            (756, "Shiinotic", 7, null),
            (757, "Salandit", 7, null),
            (758, "Salazzle", 7, null),
            (759, "Stufful", 7, null),
            (760, "Bewear", 7, null),
            (761, "Bounsweet", 7, null),
            (762, "Steenee", 7, null),
            (763, "Tsareena", 7, null),
            (764, "Comfey", 7, null),
            (765, "Oranguru", 7, null),
            (766, "Passimian", 7, null),
            (767, "Wimpod", 7, null),
            (768, "Golisopod", 7, null),
            (769, "Sandygast", 7, null),
            (770, "Palossand", 7, null),
            (771, "Pyukumuku", 7, null),
            (772, "Type: Null", 7, null),
            (773, "Silvally", 7, null),
            (774, "Minior", 7, null),
            (775, "Komala", 7, null),
            (776, "Turtonator", 7, null),
            (777, "Togedemaru", 7, null),
            (778, "Mimikyu", 7, null),
            (779, "Bruxish", 7, null),
            (780, "Drampa", 7, null),
            (781, "Dhelmise", 7, null),
            (782, "Jangmo-o", 7, null),
            (783, "Hakamo-o", 7, null),
            (784, "Kommo-o", 7, null),
            (785, "Tapu Koko", 7, null),
            (786, "Tapu Lele", 7, null),
            (787, "Tapu Bulu", 7, null),
            (788, "Tapu Fini", 7, null),
            (789, "Cosmog", 7, null),
            (790, "Cosmoem", 7, null),
            (791, "Solgaleo", 7, null),
            (792, "Lunala", 7, null),
            (793, "Nihilego", 7, null),
            (794, "Buzzwole", 7, null),
            (795, "Pheromosa", 7, null),
            (796, "Xurkitree", 7, null),
            (797, "Celesteela", 7, null),
            (798, "Kartana", 7, null),
            (799, "Guzzlord", 7, null),
            (800, "Necrozma", 7, null),
            (801, "Magearna", 7, null),
            (802, "Marshadow", 7, null),
            (803, "Poipole", 7, null),
            (804, "Naganadel", 7, null),
            (805, "Stakataka", 7, null),
            (806, "Blacephalon", 7, null),
            (807, "Zeraora", 7, null),
            (808, "Meltan", 7, null),
            (809, "Melmetal", 7, null),

            // Generation VIII (Galar) #810-905
            (810, "Grookey", 8, null),
            (811, "Thwackey", 8, null),
            (812, "Rillaboom", 8, null),
            (813, "Scorbunny", 8, null),
            (814, "Raboot", 8, null),
            (815, "Cinderace", 8, null),
            (816, "Sobble", 8, null),
            (817, "Drizzile", 8, null),
            (818, "Inteleon", 8, null),
            (819, "Skwovet", 8, null),
            (820, "Greedent", 8, null),
            (821, "Rookidee", 8, null),
            (822, "Corvisquire", 8, null),
            (823, "Corviknight", 8, null),
            (824, "Blipbug", 8, null),
            (825, "Dottler", 8, null),
            (826, "Orbeetle", 8, null),
            (827, "Nickit", 8, null),
            (828, "Thievul", 8, null),
            (829, "Gossifleur", 8, null),
            (830, "Eldegoss", 8, null),
            (831, "Wooloo", 8, null),
            (832, "Dubwool", 8, null),
            (833, "Chewtle", 8, null),
            (834, "Drednaw", 8, null),
            (835, "Yamper", 8, null),
            (836, "Boltund", 8, null),
            (837, "Rolycoly", 8, null),
            (838, "Carkol", 8, null),
            (839, "Coalossal", 8, null),
            (840, "Applin", 8, null),
            (841, "Flapple", 8, null),
            (842, "Appletun", 8, null),
            (843, "Silicobra", 8, null),
            (844, "Sandaconda", 8, null),
            (845, "Cramorant", 8, null),
            (846, "Arrokuda", 8, null),
            (847, "Barraskewda", 8, null),
            (848, "Toxel", 8, null),
            (849, "Toxtricity", 8, null),
            (850, "Sizzlipede", 8, null),
            (851, "Centiskorch", 8, null),
            (852, "Clobbopus", 8, null),
            (853, "Grapploct", 8, null),
            (854, "Sinistea", 8, null),
            (855, "Polteageist", 8, null),
            (856, "Hatenna", 8, null),
            (857, "Hattrem", 8, null),
            (858, "Hatterene", 8, null),
            (859, "Impidimp", 8, null),
            (860, "Morgrem", 8, null),
            (861, "Grimmsnarl", 8, null),
            (862, "Obstagoon", 8, null),
            (863, "Perrserker", 8, null),
            (864, "Cursola", 8, null),
            (865, "Sirfetch'd", 8, null),
            (866, "Mr. Rime", 8, null),
            (867, "Runerigus", 8, null),
            (868, "Milcery", 8, null),
            (869, "Alcremie", 8, null),
            (870, "Falinks", 8, null),
            (871, "Pincurchin", 8, null),
            (872, "Snom", 8, null),
            (873, "Frosmoth", 8, null),
            (874, "Stonjourner", 8, null),
            (875, "Eiscue", 8, null),
            (876, "Indeedee", 8, null),
            (877, "Morpeko", 8, null),
            (878, "Cufant", 8, null),
            (879, "Copperajah", 8, null),
            (880, "Dracozolt", 8, null),
            (881, "Arctozolt", 8, null),
            (882, "Dracovish", 8, null),
            (883, "Arctovish", 8, null),
            (884, "Duraludon", 8, null),
            (885, "Dreepy", 8, null),
            (886, "Drakloak", 8, null),
            (887, "Dragapult", 8, null),
            (888, "Zacian", 8, null),
            (889, "Zamazenta", 8, null),
            (890, "Eternatus", 8, null),
            (891, "Kubfu", 8, null),
            (892, "Urshifu", 8, null),
            (893, "Zarude", 8, null),
            (894, "Regieleki", 8, null),
            (895, "Regidrago", 8, null),
            (896, "Glastrier", 8, null),
            (897, "Spectrier", 8, null),
            (898, "Calyrex", 8, null),
            (899, "Wyrdeer", 8, null),
            (900, "Kleavor", 8, null),
            (901, "Ursaluna", 8, null),
            (902, "Basculegion", 8, null),
            (903, "Sneasler", 8, null),
            (904, "Overqwil", 8, null),
            (905, "Enamorus", 8, null),

            // Generation IX (Paldea) #906-1025
            (906, "Sprigatito", 9, null),
            (907, "Floragato", 9, null),
            (908, "Meowscarada", 9, null),
            (909, "Fuecoco", 9, null),
            (910, "Crocalor", 9, null),
            (911, "Skeledirge", 9, null),
            (912, "Quaxly", 9, null),
            (913, "Quaxwell", 9, null),
            (914, "Quaquaval", 9, null),
            (915, "Lechonk", 9, null),
            (916, "Oinkologne", 9, null),
            (917, "Tarountula", 9, null),
            (918, "Spidops", 9, null),
            (919, "Nymble", 9, null),
            (920, "Lokix", 9, null),
            (921, "Pawmi", 9, null),
            (922, "Pawmo", 9, null),
            (923, "Pawmot", 9, null),
            (924, "Tandemaus", 9, null),
            (925, "Maushold", 9, null),
            (926, "Fidough", 9, null),
            (927, "Dachsbun", 9, null),
            (928, "Smoliv", 9, null),
            (929, "Dolliv", 9, null),
            (930, "Arboliva", 9, null),
            (931, "Squawkabilly", 9, null),
            (932, "Nacli", 9, null),
            (933, "Naclstack", 9, null),
            (934, "Garganacl", 9, null),
            (935, "Charcadet", 9, null),
            (936, "Armarouge", 9, null),
            (937, "Ceruledge", 9, null),
            (938, "Tadbulb", 9, null),
            (939, "Bellibolt", 9, null),
            (940, "Wattrel", 9, null),
            (941, "Kilowattrel", 9, null),
            (942, "Maschiff", 9, null),
            (943, "Mabosstiff", 9, null),
            (944, "Shroodle", 9, null),
            (945, "Grafaiai", 9, null),
            (946, "Bramblin", 9, null),
            (947, "Brambleghast", 9, null),
            (948, "Toedscool", 9, null),
            (949, "Toedscruel", 9, null),
            (950, "Klawf", 9, null),
            (951, "Capsakid", 9, null),
            (952, "Scovillain", 9, null),
            (953, "Rellor", 9, null),
            (954, "Rabsca", 9, null),
            (955, "Flittle", 9, null),
            (956, "Espathra", 9, null),
            (957, "Tinkatink", 9, null),
            (958, "Tinkatuff", 9, null),
            (959, "Tinkaton", 9, null),
            (960, "Wiglett", 9, null),
            (961, "Wugtrio", 9, null),
            (962, "Bombirdier", 9, null),
            (963, "Finizen", 9, null),
            (964, "Palafin", 9, null),
            (965, "Varoom", 9, null),
            (966, "Revavroom", 9, null),
            (967, "Cyclizar", 9, null),
            (968, "Orthworm", 9, null),
            (969, "Glimmet", 9, null),
            (970, "Glimmora", 9, null),
            (971, "Greavard", 9, null),
            (972, "Houndstone", 9, null),
            (973, "Flamigo", 9, null),
            (974, "Cetoddle", 9, null),
            (975, "Cetitan", 9, null),
            (976, "Veluza", 9, null),
            (977, "Dondozo", 9, null),
            (978, "Tatsugiri", 9, null),
            (979, "Annihilape", 9, null),
            (980, "Clodsire", 9, null),
            (981, "Farigiraf", 9, null),
            (982, "Dudunsparce", 9, null),
            (983, "Kingambit", 9, null),
            (984, "Great Tusk", 9, null),
            (985, "Scream Tail", 9, null),
            (986, "Brute Bonnet", 9, null),
            (987, "Flutter Mane", 9, null),
            (988, "Slither Wing", 9, null),
            (989, "Sandy Shocks", 9, null),
            (990, "Iron Treads", 9, null),
            (991, "Iron Bundle", 9, null),
            (992, "Iron Hands", 9, null),
            (993, "Iron Jugulis", 9, null),
            (994, "Iron Moth", 9, null),
            (995, "Iron Thorns", 9, null),
            (996, "Frigibax", 9, null),
            (997, "Arctibax", 9, null),
            (998, "Baxcalibur", 9, null),
            (999, "Gimmighoul", 9, null),
            (1000, "Gholdengo", 9, null),
            (1001, "Wo-Chien", 9, null),
            (1002, "Chien-Pao", 9, null),
            (1003, "Ting-Lu", 9, null),
            (1004, "Chi-Yu", 9, null),
            (1005, "Roaring Moon", 9, null),
            (1006, "Iron Valiant", 9, null),
            (1007, "Koraidon", 9, null),
            (1008, "Miraidon", 9, null),
            (1009, "Walking Wake", 9, null),
            (1010, "Iron Leaves", 9, null),
            (1011, "Dipplin", 9, null),
            (1012, "Poltchageist", 9, null),
            (1013, "Sinistcha", 9, null),
            (1014, "Okidogi", 9, null),
            (1015, "Munkidori", 9, null),
            (1016, "Fezandipiti", 9, null),
            (1017, "Ogerpon", 9, null),
            (1018, "Archaludon", 9, null),
            (1019, "Hydrapple", 9, null),
            (1020, "Gouging Fire", 9, null),
            (1021, "Raging Bolt", 9, null),
            (1022, "Iron Boulder", 9, null),
            (1023, "Iron Crown", 9, null),
            (1024, "Terapagos", 9, null),
            (1025, "Pecharunt", 9, null),

            // Mega Evolutions (Generation VI-VII)
            (3, "Mega Venusaur", 6, null),
            (6, "Mega Charizard X", 6, null),
            (6, "Mega Charizard Y", 6, null),
            (9, "Mega Blastoise", 6, null),
            (15, "Mega Beedrill", 6, null),
            (18, "Mega Pidgeot", 6, null),
            (65, "Mega Alakazam", 6, null),
            (80, "Mega Slowbro", 6, null),
            (94, "Mega Gengar", 6, null),
            (115, "Mega Kangaskhan", 6, null),
            (127, "Mega Pinsir", 6, null),
            (130, "Mega Gyarados", 6, null),
            (142, "Mega Aerodactyl", 6, null),
            (150, "Mega Mewtwo X", 6, null),
            (150, "Mega Mewtwo Y", 6, null),
            (181, "Mega Ampharos", 6, null),
            (208, "Mega Steelix", 6, null),
            (212, "Mega Scizor", 6, null),
            (214, "Mega Heracross", 6, null),
            (229, "Mega Houndoom", 6, null),
            (248, "Mega Tyranitar", 6, null),
            (254, "Mega Sceptile", 6, null),
            (257, "Mega Blaziken", 6, null),
            (260, "Mega Swampert", 6, null),
            (282, "Mega Gardevoir", 6, null),
            (302, "Mega Sableye", 6, null),
            (303, "Mega Mawile", 6, null),
            (306, "Mega Aggron", 6, null),
            (308, "Mega Medicham", 6, null),
            (310, "Mega Manectric", 6, null),
            (319, "Mega Sharpedo", 6, null),
            (323, "Mega Camerupt", 6, null),
            (334, "Mega Altaria", 6, null),
            (354, "Mega Banette", 6, null),
            (359, "Mega Absol", 6, null),
            (362, "Mega Glalie", 6, null),
            (373, "Mega Salamence", 6, null),
            (376, "Mega Metagross", 6, null),
            (380, "Mega Latias", 6, null),
            (381, "Mega Latios", 6, null),
            (382, "Primal Kyogre", 6, null),
            (383, "Primal Groudon", 6, null),
            (384, "Mega Rayquaza", 6, null),
            (428, "Mega Lopunny", 6, null),
            (445, "Mega Garchomp", 6, null),
            (448, "Mega Lucario", 6, null),
            (460, "Mega Abomasnow", 6, null),
            (475, "Mega Gallade", 6, null),
            (531, "Mega Audino", 6, null),
            (719, "Mega Diancie", 6, null),

            // Alolan Forms (Generation VII)
            (19, "Alolan Rattata", 7, null),
            (20, "Alolan Raticate", 7, null),
            (26, "Alolan Raichu", 7, null),
            (27, "Alolan Sandshrew", 7, null),
            (28, "Alolan Sandslash", 7, null),
            (37, "Alolan Vulpix", 7, null),
            (38, "Alolan Ninetales", 7, null),
            (50, "Alolan Diglett", 7, null),
            (51, "Alolan Dugtrio", 7, null),
            (52, "Alolan Meowth", 7, null),
            (53, "Alolan Persian", 7, null),
            (74, "Alolan Geodude", 7, null),
            (75, "Alolan Graveler", 7, null),
            (76, "Alolan Golem", 7, null),
            (88, "Alolan Grimer", 7, null),
            (89, "Alolan Muk", 7, null),
            (103, "Alolan Exeggutor", 7, null),
            (105, "Alolan Marowak", 7, null),

            // Galarian Forms (Generation VIII)
            (52, "Galarian Meowth", 8, null),
            (77, "Galarian Ponyta", 8, null),
            (78, "Galarian Rapidash", 8, null),
            (79, "Galarian Slowpoke", 8, null),
            (80, "Galarian Slowbro", 8, null),
            (83, "Galarian Farfetch'd", 8, null),
            (110, "Galarian Weezing", 8, null),
            (122, "Galarian Mr. Mime", 8, null),
            (144, "Galarian Articuno", 8, null),
            (145, "Galarian Zapdos", 8, null),
            (146, "Galarian Moltres", 8, null),
            (199, "Galarian Slowking", 8, null),
            (222, "Galarian Corsola", 8, null),
            (263, "Galarian Zigzagoon", 8, null),
            (264, "Galarian Linoone", 8, null),
            (554, "Galarian Darumaka", 8, null),
            (555, "Galarian Darmanitan", 8, null),
            (562, "Galarian Yamask", 8, null),
            (618, "Galarian Stunfisk", 8, null),

            // Hisuian Forms (Generation VIII)
            (58, "Hisuian Growlithe", 8, null),
            (59, "Hisuian Arcanine", 8, null),
            (100, "Hisuian Voltorb", 8, null),
            (101, "Hisuian Electrode", 8, null),
            (157, "Hisuian Typhlosion", 8, null),
            (211, "Hisuian Qwilfish", 8, null),
            (215, "Hisuian Sneasel", 8, null),
            (503, "Hisuian Samurott", 8, null),
            (549, "Hisuian Lilligant", 8, null),
            (570, "Hisuian Zorua", 8, null),
            (571, "Hisuian Zoroark", 8, null),
            (628, "Hisuian Braviary", 8, null),
            (705, "Hisuian Sliggoo", 8, null),
            (706, "Hisuian Goodra", 8, null),
            (713, "Hisuian Avalugg", 8, null),
            (724, "Hisuian Decidueye", 8, null),

            // Paldean Forms (Generation IX)
            (128, "Paldean Tauros", 9, null),
            (128, "Paldean Tauros (Blaze Breed)", 9, null),
            (128, "Paldean Tauros (Aqua Breed)", 9, null),
            (194, "Paldean Wooper", 9, null),

            // Gigantamax Forms (Generation VIII)
            (6, "Gigantamax Charizard", 8, "Charizard VMAX"),
            (12, "Gigantamax Butterfree", 8, "Butterfree VMAX"),
            (25, "Gigantamax Pikachu", 8, "Pikachu VMAX"),
            (52, "Gigantamax Meowth", 8, "Meowth VMAX"),
            (68, "Gigantamax Machamp", 8, "Machamp VMAX"),
            (94, "Gigantamax Gengar", 8, "Gengar VMAX"),
            (99, "Gigantamax Kingler", 8, "Kingler VMAX"),
            (131, "Gigantamax Lapras", 8, "Lapras VMAX"),
            (133, "Gigantamax Eevee", 8, "Eevee VMAX"),
            (143, "Gigantamax Snorlax", 8, "Snorlax VMAX"),
            (569, "Gigantamax Garbodor", 8, "Garbodor VMAX"),
            (809, "Gigantamax Melmetal", 8, "Melmetal VMAX"),
            (812, "Gigantamax Rillaboom", 8, "Rillaboom VMAX"),
            (815, "Gigantamax Cinderace", 8, "Cinderace VMAX"),
            (818, "Gigantamax Inteleon", 8, "Inteleon VMAX"),
            (823, "Gigantamax Corviknight", 8, "Corviknight VMAX"),
            (826, "Gigantamax Orbeetle", 8, "Orbeetle VMAX"),
            (834, "Gigantamax Drednaw", 8, "Drednaw VMAX"),
            (839, "Gigantamax Coalossal", 8, "Coalossal VMAX"),
            (841, "Gigantamax Flapple", 8, "Flapple VMAX"),
            (842, "Gigantamax Appletun", 8, "Appletun VMAX"),
            (844, "Gigantamax Sandaconda", 8, "Sandaconda VMAX"),
            (849, "Gigantamax Toxtricity", 8, "Toxtricity VMAX"),
            (851, "Gigantamax Centiskorch", 8, "Centiskorch VMAX"),
            (858, "Gigantamax Hatterene", 8, "Hatterene VMAX"),
            (861, "Gigantamax Grimmsnarl", 8, "Grimmsnarl VMAX"),
            (869, "Gigantamax Alcremie", 8, "Alcremie VMAX"),
            (879, "Gigantamax Copperajah", 8, "Copperajah VMAX"),
            (884, "Gigantamax Duraludon", 8, "Duraludon VMAX"),
            (892, "Gigantamax Urshifu", 8, "Urshifu VMAX"),
        ];
    }
}
