using FluentMigrator;

namespace PokeBinder.FluentMigrator.Migrations.TcgCatalog;

[Migration(20250325_000003)]
[Tags(DatabaseTags.TcgCatalog)]
public class CreateRarityBySetFilterOption : Migration
{
    public override void Up()
    {
        Create.Table("rarityBySetFilterOption")
            .WithColumn("id").AsInt32().PrimaryKey().Identity()
            .WithColumn("setId").AsInt32().NotNullable()
                .ForeignKey("FK_rarityBySetFilterOption_sets", "sets", "id")
            .WithColumn("rarity").AsString(127).NotNullable();

        foreach (var (setId, rarity) in GetSeedData())
        {
            Insert.IntoTable("rarityBySetFilterOption").Row(new
            {
                setId,
                rarity
            });
        }
    }

    public override void Down()
    {
        Delete.Table("rarityBySetFilterOption");
    }

    private static List<(int SetId, string Rarity)> GetSeedData()
    {
        return
        [
            (20, "Common"),
            (20, "Double Rare"),
            (20, "Illustration Rare"),
            (20, "Mega Attack Rare"),
            (20, "Mega Hyper Rare"),
            (20, "Rare"),
            (20, "Special Illustration Rare"),
            (20, "Ultra Rare"),
            (20, "Uncommon"),
            (19, "Common"),
            (19, "Double Rare"),
            (19, "Holo Rare"),
            (19, "Illustration Rare"),
            (19, "Mega Hyper Rare"),
            (19, "Rare"),
            (19, "Special Illustration Rare"),
            (19, "Ultra Rare"),
            (19, "Uncommon"),
            (18, "Common"),
            (18, "Double Rare"),
            (18, "Illustration Rare"),
            (18, "Mega Hyper Rare"),
            (18, "Promo"),
            (18, "Rare"),
            (18, "Special Illustration Rare"),
            (18, "Ultra Rare"),
            (18, "Uncommon"),
            (17, "Holo Rare"),
            (17, "Illustration Rare"),
            (17, "Promo"),
            (16, "Black White Rare"),
            (16, "Common"),
            (16, "Double Rare"),
            (16, "Holo Rare"),
            (16, "Illustration Rare"),
            (16, "Rare"),
            (16, "Special Illustration Rare"),
            (16, "Ultra Rare"),
            (16, "Uncommon"),
            (14, "Common"),
            (14, "Double Rare"),
            (14, "Hyper Rare"),
            (14, "Illustration Rare"),
            (14, "Rare"),
            (14, "Special Illustration Rare"),
            (14, "Ultra Rare"),
            (14, "Uncommon"),
            (13, "Common"),
            (13, "Double Rare"),
            (13, "Hyper Rare"),
            (13, "Illustration Rare"),
            (13, "Rare"),
            (13, "Special Illustration Rare"),
            (13, "Ultra Rare"),
            (13, "Uncommon"),
            (4, "Common"),
            (4, "Double Rare"),
            (4, "Hyper Rare"),
            (4, "Illustration Rare"),
            (4, "Rare"),
            (4, "Special Illustration Rare"),
            (4, "Ultra Rare"),
            (4, "Uncommon"),
            (3, "Common"),
            (3, "Double Rare"),
            (3, "Hyper Rare"),
            (3, "Illustration Rare"),
            (3, "Rare"),
            (3, "Special Illustration Rare"),
            (3, "Ultra Rare"),
            (3, "Uncommon"),
            (6, "Common"),
            (6, "Double Rare"),
            (6, "Hyper Rare"),
            (6, "Illustration Rare"),
            (6, "Rare"),
            (6, "Shiny Rare"),
            (6, "Shiny Ultra Rare"),
            (6, "Special Illustration Rare"),
            (6, "Ultra Rare"),
            (6, "Uncommon"),
            (5, "Common"),
            (5, "Double Rare"),
            (5, "Hyper Rare"),
            (5, "Illustration Rare"),
            (5, "Rare"),
            (5, "Special Illustration Rare"),
            (5, "Ultra Rare"),
            (5, "Uncommon"),
            (12, "ACE SPEC Rare"),
            (12, "Common"),
            (12, "Double Rare"),
            (12, "Hyper Rare"),
            (12, "Rare"),
            (12, "Special Illustration Rare"),
            (12, "Ultra Rare"),
            (12, "Uncommon"),
            (1, "Black White Rare"),
            (1, "Common"),
            (1, "Double Rare"),
            (1, "Illustration Rare"),
            (1, "Rare"),
            (1, "Special Illustration Rare"),
            (1, "Ultra Rare"),
            (1, "Uncommon"),
            (2, "Common"),
            (2, "Double Rare"),
            (2, "Hyper Rare"),
            (2, "Illustration Rare"),
            (2, "Rare"),
            (2, "Special Illustration Rare"),
            (2, "Ultra Rare"),
            (2, "Uncommon"),
            (9, "ACE SPEC Rare"),
            (9, "Common"),
            (9, "Double Rare"),
            (9, "Hyper Rare"),
            (9, "Illustration Rare"),
            (9, "Rare"),
            (9, "Special Illustration Rare"),
            (9, "Ultra Rare"),
            (9, "Uncommon"),
            (10, "ACE SPEC Rare"),
            (10, "Common"),
            (10, "Double Rare"),
            (10, "Hyper Rare"),
            (10, "Illustration Rare"),
            (10, "Rare"),
            (10, "Special Illustration Rare"),
            (10, "Ultra Rare"),
            (10, "Uncommon"),
            (11, "ACE SPEC Rare"),
            (11, "Common"),
            (11, "Double Rare"),
            (11, "Hyper Rare"),
            (11, "Illustration Rare"),
            (11, "Rare"),
            (11, "Special Illustration Rare"),
            (11, "Ultra Rare"),
            (11, "Uncommon"),
            (7, "ACE SPEC Rare"),
            (7, "Common"),
            (7, "Double Rare"),
            (7, "Hyper Rare"),
            (7, "Illustration Rare"),
            (7, "Rare"),
            (7, "Special Illustration Rare"),
            (7, "Ultra Rare"),
            (7, "Uncommon"),
            (8, "ACE SPEC Rare"),
            (8, "Common"),
            (8, "Double Rare"),
            (8, "Hyper Rare"),
            (8, "Illustration Rare"),
            (8, "Rare"),
            (8, "Special Illustration Rare"),
            (8, "Ultra Rare"),
            (8, "Uncommon"),
            (47, "Common"),
            (47, "Holo Rare"),
            (47, "Prism Rare"),
            (47, "Rainbow Rare"),
            (47, "Rare"),
            (47, "Secret Rare"),
            (47, "Ultra Rare"),
            (47, "Uncommon"),
            (55, "Common"),
            (55, "Holo Rare"),
            (55, "Rainbow Rare"),
            (55, "Rare"),
            (55, "Secret Rare"),
            (55, "Ultra Rare"),
            (55, "Uncommon"),
            (44, "Common"),
            (44, "Holo Rare"),
            (44, "Rare"),
            (44, "Secret Rare"),
            (44, "Ultra Rare"),
            (44, "Uncommon"),
            (51, "Common"),
            (51, "Holo Rare"),
            (51, "Rare"),
            (48, "Common"),
            (48, "Holo Rare"),
            (48, "Prism Rare"),
            (48, "Secret Rare"),
            (48, "Ultra Rare"),
            (48, "Uncommon"),
            (46, "Common"),
            (46, "Holo Rare"),
            (46, "Prism Rare"),
            (46, "Rare"),
            (46, "Secret Rare"),
            (46, "Ultra Rare"),
            (46, "Uncommon"),
            (41, "Common"),
            (41, "Holo Rare"),
            (41, "Rainbow Rare"),
            (41, "Rare"),
            (41, "Secret Rare"),
            (41, "Ultra Rare"),
            (41, "Uncommon"),
            (54, "Common"),
            (54, "Holo Rare"),
            (54, "Rare"),
            (54, "Secret Rare"),
            (54, "Ultra Rare"),
            (54, "Uncommon"),
            (49, "Common"),
            (49, "Holo Rare"),
            (49, "Prism Rare"),
            (49, "Rare"),
            (49, "Secret Rare"),
            (49, "Ultra Rare"),
            (49, "Uncommon"),
            (39, "Promo"),
            (39, "Uncommon"),
            (43, "Common"),
            (43, "Holo Rare"),
            (43, "Secret Rare"),
            (43, "Shiny Holo Rare"),
            (43, "Ultra Rare"),
            (43, "Uncommon"),
            (40, "Common"),
            (40, "Holo Rare"),
            (40, "Rare"),
            (40, "Secret Rare"),
            (40, "Ultra Rare"),
            (40, "Uncommon"),
            (50, "Common"),
            (50, "Holo Rare"),
            (50, "Prism Rare"),
            (50, "Rare"),
            (50, "Secret Rare"),
            (50, "Ultra Rare"),
            (50, "Uncommon"),
            (45, "Common"),
            (45, "Holo Rare"),
            (45, "Prism Rare"),
            (45, "Rare"),
            (45, "Secret Rare"),
            (45, "Ultra Rare"),
            (45, "Uncommon"),
            (52, "Common"),
            (52, "Holo Rare"),
            (52, "Rare"),
            (52, "Secret Rare"),
            (52, "Ultra Rare"),
            (52, "Uncommon"),
            (53, "Common"),
            (53, "Holo Rare"),
            (53, "Rare"),
            (53, "Secret Rare"),
            (53, "Ultra Rare"),
            (53, "Uncommon"),
            (34, "Common"),
            (34, "Holo Rare"),
            (34, "Radiant Rare"),
            (34, "Rare"),
            (34, "Secret Rare"),
            (34, "Ultra Rare"),
            (34, "Uncommon"),
            (28, "Common"),
            (28, "Holo Rare"),
            (28, "Rare"),
            (28, "Secret Rare"),
            (28, "Ultra Rare"),
            (28, "Uncommon"),
            (33, "Common"),
            (33, "Holo Rare"),
            (33, "Promo"),
            (33, "Rare"),
            (33, "Secret Rare"),
            (33, "Ultra Rare"),
            (33, "Uncommon"),
            (31, "Classic Collection"),
            (31, "Holo Rare"),
            (31, "Promo"),
            (31, "Secret Rare"),
            (31, "Ultra Rare"),
            (25, "Common"),
            (25, "Holo Rare"),
            (25, "Secret Rare"),
            (25, "Ultra Rare"),
            (25, "Uncommon"),
            (29, "Common"),
            (29, "Holo Rare"),
            (29, "Rare"),
            (29, "Secret Rare"),
            (29, "Ultra Rare"),
            (29, "Uncommon"),
            (38, "Common"),
            (38, "Holo Rare"),
            (38, "Radiant Rare"),
            (38, "Rare"),
            (38, "Secret Rare"),
            (38, "Ultra Rare"),
            (38, "Uncommon"),
            (24, "Common"),
            (24, "Holo Rare"),
            (24, "Rare"),
            (24, "Secret Rare"),
            (24, "Ultra Rare"),
            (24, "Uncommon"),
            (30, "Common"),
            (30, "Holo Rare"),
            (30, "Rare"),
            (30, "Secret Rare"),
            (30, "Ultra Rare"),
            (30, "Uncommon"),
            (32, "Common"),
            (32, "Holo Rare"),
            (32, "Rare"),
            (32, "Secret Rare"),
            (32, "Ultra Rare"),
            (32, "Uncommon"),
            (36, "Common"),
            (36, "Holo Rare"),
            (36, "Radiant Rare"),
            (36, "Rare"),
            (36, "Secret Rare"),
            (36, "Ultra Rare"),
            (36, "Uncommon"),
            (35, "Common"),
            (35, "Holo Rare"),
            (35, "Radiant Rare"),
            (35, "Secret Rare"),
            (35, "Ultra Rare"),
            (35, "Uncommon"),
            (23, "Common"),
            (23, "Holo Rare"),
            (23, "Rare"),
            (23, "Secret Rare"),
            (23, "Ultra Rare"),
            (23, "Uncommon"),
            (21, "Holo Rare"),
            (21, "Promo"),
            (21, "Ultra Rare"),
            (27, "Amazing Rare"),
            (27, "Common"),
            (27, "Holo Rare"),
            (27, "Rare"),
            (27, "Secret Rare"),
            (27, "Shiny Holo Rare"),
            (27, "Ultra Rare"),
            (27, "Uncommon"),
            (37, "Common"),
            (37, "Holo Rare"),
            (37, "Radiant Rare"),
            (37, "Rare"),
            (37, "Secret Rare"),
            (37, "Ultra Rare"),
            (37, "Uncommon"),
            (22, "Common"),
            (22, "Holo Rare"),
            (22, "Rare"),
            (22, "Secret Rare"),
            (22, "Ultra Rare"),
            (22, "Uncommon"),
            (26, "Amazing Rare"),
            (26, "Common"),
            (26, "Holo Rare"),
            (26, "Rare"),
            (26, "Secret Rare"),
            (26, "Ultra Rare"),
            (26, "Uncommon")
        ];
    }
}
